package utils.reasonercomparator;

/** methods to measure */
public enum MethodNames {
    //@formatter:off
    /** precomputeInferences */  precomputeInferences,
    /** isConsistent */  isConsistent,
    /** isSatisfiable */  isSatisfiable,
    /** getUnsatisfiableClasses */  getUnsatisfiableClasses,
    /** isEntailed */  isEntailed,
    /** getSubClasses */  getSubClasses,
    /** getSuperClasses */  getSuperClasses,
    /** getEquivalentClasses */  getEquivalentClasses,
    /** getDisjointClasses */  getDisjointClasses,
    /** getTopObjectPropertyNode */  getTopObjectPropertyNode,
    /** getBottomObjectPropertyNode */  getBottomObjectPropertyNode,
    /** getSubObjectProperties */  getSubObjectProperties,
    /** getSuperObjectProperties */  getSuperObjectProperties,
    /** getEquivalentObjectProperties */  getEquivalentObjectProperties,
    /** getDisjointObjectProperties */  getDisjointObjectProperties,
    /** getInverseObjectProperties */  getInverseObjectProperties,
    /** getObjectPropertyDomains */  getObjectPropertyDomains,
    /** getObjectPropertyRanges */  getObjectPropertyRanges,
    /** getTopDataPropertyNode */  getTopDataPropertyNode,
    /** getBottomDataPropertyNode */  getBottomDataPropertyNode,
    /** getSubDataProperties */  getSubDataProperties,
    /** getSuperDataProperties */  getSuperDataProperties,
    /** getEquivalentDataProperties */  getEquivalentDataProperties,
    /** getDisjointDataProperties */  getDisjointDataProperties,
    /** getDataPropertyDomains */  getDataPropertyDomains,
    /** getTypes */  getTypes,
    /** getInstances */  getInstances,
    /** getObjectPropertyValues */  getObjectPropertyValues,
    /** getDataPropertyValues */  getDataPropertyValues,
    /** getSameIndividuals */  getSameIndividuals,
    /** getDifferentIndividuals */  getDifferentIndividuals,
    /** getTopClassNode */  getTopClassNode,
    /** getBottomClassNode */  getBottomClassNode,
    /** init */  init,
    /** isEntailmentCheckingSupported */  isEntailmentCheckingSupported,
    /** getTimeOut */  getTimeOut,
    /** getFreshEntityPolicy */  getFreshEntityPolicy,
    /** getIndividualNodeSetPolicy */  getIndividualNodeSetPolicy,
    /** interrupt */  interrupt,
    /** dispose */  dispose,
    /** flush */  flush,
    /** isPrecomputed */  isPrecomputed,
    /** getPrecomputableInferenceTypes */  getPrecomputableInferenceTypes,
    /** getPendingChanges */  getPendingChanges,
    /** getPendingAxiomAdditions */  getPendingAxiomAdditions,
    /** getPendingAxiomRemovals */  getPendingAxiomRemovals
    //@formatter:on
}
